# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: i30's blog
email: contact.dangvu@gmail.com
description: Some thoughts while caffeine is loading...
baseurl: ""
url: "http://127.0.0.1:4000"
twitter_username: i30
github_username:  i30

# Build settings
markdown: kramdown
