# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minh Tri Vu
email: minhtri.contact@gmail.com
description: "Some thoughts while caffeine is loading..."
baseurl: ""
url: "http://minhtri.org"
twitter_username: minhtri_vu
github_username: i30
permalink: none
collections:
  books:

# Build settings
markdown: kramdown
